### Learn about numpy

In [6]:
import numpy as np

### Creating an Array from list 

In [7]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2d Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2d Array:
 [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [8]:
py_list = [1, 2, 3]
print("Python list multiplication:", py_list * 2)


np_array = np.array([1, 2, 3])
print("Python array multiplication:", np_array * 2) 

Python list multiplication: [1, 2, 3, 1, 2, 3]
Python array multiplication: [2 4 6]


### Creating array from scratch

In [9]:
Zeros = np.zeros((3, 2))
print("Zero Array:\n", Zeros)

Ones = np.ones((2, 3 ))
print("One array:\n", Ones)

full = np.full((2,3), 5)
print("Matrice of 5 :\n", full)

random = np.random.random((2,3))
print("Random array:\n", random)

sequence = np.arange(0, 151, 15)
print("Sequence array:\n", sequence)

Zero Array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
One array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Matrice of 5 :
 [[5 5 5]
 [5 5 5]]
Random array:
 [[0.0495303  0.27009382 0.18398408]
 [0.60732715 0.72574885 0.26597423]]
Sequence array:
 [  0  15  30  45  60  75  90 105 120 135 150]


### Array Properties

In [10]:
arr = np.array([[1, 2, 3],[5, 6, 7]])
print("Array:", arr)
print("Shapeof the array:", arr.shape)
print("Size of the array:", arr.size)
print("Dimension of the array:", arr.ndim)
print("Data type of the array:", arr.dtype)

Array: [[1 2 3]
 [5 6 7]]
Shapeof the array: (2, 3)
Size of the array: 6
Dimension of the array: 2
Data type of the array: int64


### Array Reshaping

In [11]:
arr = np.array([[1, 2, 3, 4, 5, 6],
                 [7, 8, 9, 10, 11, 12]])
print("Original array:\n", arr)

reshaped = arr.reshape(1, 12)
print("Reshaped array:\n", reshaped)

flattened = reshaped.flatten()
print("Flattened array:\n", flattened)

raveled = reshaped.ravel()
print("Raveled array:\n", raveled)

transpose = arr.T
print("Transpose array:\n", transpose)
print("Transpose array ")






Original array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Reshaped array:
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
Flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Transpose array:
 [[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
Transpose array 


In [12]:
full = np.full((4,5), 7)
print("Original array:\n", full)

reshaped = full.reshape((10, 2))
print("Reshaped array:\n", reshaped) 


Original array:
 [[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
Reshaped array:
 [[7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]]


In [13]:
try:
    data = np.arange(16)
    print("Original array:\n", data)

    reshaped = data.reshape((4, 4))
    print("Reshaped array:\n", reshaped)
except:
    print("Reshape failed cause there is a error in a code ")

Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Numpy Array operations

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print("Basic slicing", arr[2:8])
print("with step", arr[0:8:2])
print("Negative index", arr[-3])

Basic slicing [2 3 4 5 6 7]
with step [0 2 4 6]
Negative index 6


In [15]:
arr_3d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specefic elements", arr_3d[2,0])
print("Entire row", arr_3d[2])
print("Entire column", arr_3d[:,2])



Specefic elements 7
Entire row [7 8 9]
Entire column [3 6 9]


In [16]:
arr = np.arange(181)
print("Table of 18", arr[0:181:18])

Table of 18 [  0  18  36  54  72  90 108 126 144 162 180]


### Sorting of Array

In [17]:
unsorted = np.array([2,6,4,7,5,2,1,8,1, 3,9])
print("Sorted array", np.sort(unsorted))

arr_2d = np.array([[1,2], [1,3],[3,2]])
print("Sorted array", np.sort(arr_2d, axis=0))

Sorted array [1 1 2 2 3 4 5 6 7 8 9]
Sorted array [[1 2]
 [1 2]
 [3 3]]


### Filter in array

In [18]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Even_number = numbers[numbers % 2 != 0]
print("Even number", Even_number)

#Filter with mask

mask = numbers > 6
print("Numbers greater than 6", numbers[mask])          



Even number [1 3 5 7 9]
Numbers greater than 6 [ 7  8  9 10]


### Adding and Removing Data

In [29]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
combined = np.concatenate((arr_1,arr_2))
print(combined)

[1 2 3 4 5 6]


##Array compatibility

In [30]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3 , 4])
c = np.array([1, 2, 3])

print("Compatibility shapes", a.shape == b.shape)


Compatibility shapes False


In [31]:
original = np.array([[1, 2],[3, 4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [32]:
array = np.array([1, 2, 3, 4, 5, 6])
deleted = np.delete(array, 3)
print("Array after deletion:", deleted)

Array after deletion: [1 2 3 5 6]


In [33]:
# Sales of 2021,2022,2023,2024 of these resataurant
sales_data = np.array([
    [1,   150000,   180000,   200000,   250000], # Burger farm
    [2,   300000,   40000,   560000,   500000], # Dominos
    [3,   390000,   450000,   56006,   578694], # Piza hub
])
print("==== Sales data analysis ===")
print("Shape of data\n", sales_data.shape)
print("Sample data of companies\n", sales_data[:3])



==== Sales data analysis ===
Shape of data
 (3, 5)
Sample data of companies
 [[     1 150000 180000 200000 250000]
 [     2 300000  40000 560000 500000]
 [     3 390000 450000  56006 578694]]


In [34]:
# Total sales per restaurant
print(np.sum(sales_data, axis=0))
year_total = np.sum(sales_data[:, 1:], axis=1)
print("Total sales per restaurant", year_total)

[      6  840000  670000  816006 1328694]
Total sales per restaurant [ 780000 1400000 1474700]


In [35]:
# Minimum sales per restaurant
min_sales = np.min(sales_data[:, 1:], axis=1)
print("Minimum sales of the restaurant ", min_sales)
max_sales = np.max(sales_data[:, 1:], axis=1)
print("Maximum sales of the restaurant ", max_sales)

# Avg sales per restaurant
avg_sales = np.mean(sales_data[:, 1:], axis=1)
print("Avg sales of the restaurant", avg_sales)

monthly_avg = sales_data[:, 1:] / 12
print("\nmonthly avg of the restaurant\n", monthly_avg)



Minimum sales of the restaurant  [150000  40000  56006]
Maximum sales of the restaurant  [250000 560000 578694]
Avg sales of the restaurant [195000. 350000. 368675.]

monthly avg of the restaurant
 [[12500.         15000.         16666.66666667 20833.33333333]
 [25000.          3333.33333333 46666.66666667 41666.66666667]
 [32500.         37500.          4667.16666667 48224.5       ]]


### Vector in Numpy

In [28]:
vector1 = np.array([1, 2, 3, 4])
vector2 = np.array([5, 6, 7, 8])
print("Vector Addition", vector1 + vector2)
print("\nVector multiplication",vector1 * vector2)
print("\nVector subtraction",vector1 - vector2)
print("\nVector divison",vector1 / vector2) 
print("\n Dot product", np.dot(vector1, vector2))

Vector Addition [ 6  8 10 12]

Vector multiplication [ 5 12 21 32]

Vector subtraction [-4 -4 -4 -4]

Vector divison [0.2        0.33333333 0.42857143 0.5       ]

 Dot product 70
